---
abstract: 'Dancer plugin for MongoDB'
author:
  - 'Adam Taylor <ajct@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Mongo
requires:
  Dancer::Plugin: 0
  MongoDB: 0.38
version: 0.02
